version: '2.2'
services:
  mongo:
    image: mongo
    restart: always
  jguweka:
    image: jguweka/jguweka:OAS3
    restart: always
    environment:
      CATALINA_OPTS: '-agentpath:/usr/local/jprofiler11.0/bin/linux-x64/libjprofilerti.so=port=8849,nowait'
    links:
      - "mongo:mongodb"
    ports:
      - "8081"
      - "8849"
    depends_on:
      - mongo
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"
    mem_limit: 400M
    cpus: 0.25
  lb:
    image: dockercloud/haproxy
    links:
     - jguweka
    ports:
     - '8081:80'
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
